#include "internal.hpp"

namespace dbdiff::postgresql {

namespace {

[[nodiscard]] std::string qualified_sql(const QualifiedName& name) {
  return quote_identifier(name.schema) + "." + quote_identifier(name.name);
}

[[nodiscard]] std::string qualified_identity(const QualifiedName& name) {
  return name.schema + "." + name.name;
}

[[nodiscard]] std::string column_identity(const QualifiedName& table,
                                          const std::string_view column) {
  return qualified_identity(table) + "." + std::string{column};
}

[[nodiscard]] std::string operation_id(const std::string_view action,
                                       const std::string_view identity) {
  std::string input{action};
  input.push_back('\0');
  input.append(identity);
  return "postgresql." + std::string{action} + "." + sha256_hex(input);
}

[[nodiscard]] std::string render_column_definition(const Column& column,
                                                   const bool include_not_null = true) {
  std::string sql = quote_identifier(column.name) + " " + column.type;
  if (column.collation.has_value()) {
    sql += " COLLATE " + qualified_sql(*column.collation);
  }
  if (column.generated != GeneratedStorage::none) {
    sql += " GENERATED ALWAYS AS (" + column.default_expression.value_or(std::string{}) + ") ";
    sql += column.generated == GeneratedStorage::stored ? "STORED" : "VIRTUAL";
  } else if (column.identity != IdentityGeneration::none) {
    sql += column.identity == IdentityGeneration::always ? " GENERATED ALWAYS AS IDENTITY"
                                                         : " GENERATED BY DEFAULT AS IDENTITY";
  } else if (column.default_expression.has_value()) {
    sql += " DEFAULT " + *column.default_expression;
  }
  if (column.not_null && include_not_null) {
    sql += " NOT NULL";
  }
  return sql;
}

[[nodiscard]] bool has_not_null_constraint(const std::vector<TableConstraint>& constraints,
                                           const QualifiedName& table,
                                           const std::string_view column) {
  return std::ranges::any_of(constraints, [&](const TableConstraint& constraint) {
    return constraint.table == table && constraint.kind == ConstraintKind::not_null &&
           constraint.columns.size() == 1U && constraint.columns.front() == column;
  });
}

[[nodiscard]] std::string render_create_table(const Table& table,
                                              const std::vector<TableConstraint>& constraints) {
  std::ostringstream sql;
  sql << "CREATE ";
  if (table.persistence == TablePersistence::unlogged) {
    sql << "UNLOGGED ";
  }
  sql << "TABLE " << qualified_sql(table.name) << " (";
  for (std::size_t index = 0U; index < table.columns.size(); ++index) {
    if (index != 0U) {
      sql << ", ";
    }
    sql << render_column_definition(
        table.columns[index],
        !has_not_null_constraint(constraints, table.name, table.columns[index].name));
  }
  sql << ");";
  return sql.str();
}

[[nodiscard]] std::string constraint_identity(const TableConstraint& constraint) {
  return qualified_identity(constraint.table) + ".constraint." + constraint.name;
}

[[nodiscard]] std::string render_add_constraint(const TableConstraint& constraint) {
  return "ALTER TABLE " + qualified_sql(constraint.table) + " ADD CONSTRAINT " +
         quote_identifier(constraint.name) + " " + constraint.definition + ";";
}

[[nodiscard]] std::string render_drop_constraint(const TableConstraint& constraint) {
  return "ALTER TABLE " + qualified_sql(constraint.table) + " DROP CONSTRAINT " +
         quote_identifier(constraint.name) + " RESTRICT;";
}

[[nodiscard]] std::string render_create_index(const Index& index) {
  std::ostringstream sql;
  sql << "CREATE ";
  if (index.unique) {
    sql << "UNIQUE ";
  }
  sql << "INDEX " << quote_identifier(index.name.name) << " ON " << qualified_sql(index.table)
      << " USING " << quote_identifier(index.method) << " (";
  for (std::size_t position = 0U; position < index.key_expressions.size(); ++position) {
    if (position != 0U) {
      sql << ", ";
    }
    sql << index.key_expressions[position];
  }
  sql << ')';
  if (!index.included_columns.empty()) {
    sql << " INCLUDE (";
    for (std::size_t position = 0U; position < index.included_columns.size(); ++position) {
      if (position != 0U) {
        sql << ", ";
      }
      sql << quote_identifier(index.included_columns[position]);
    }
    sql << ')';
  }
  if (index.nulls_not_distinct) {
    sql << " NULLS NOT DISTINCT";
  }
  if (index.predicate.has_value()) {
    sql << " WHERE " << *index.predicate;
  }
  sql << ';';
  return sql.str();
}

[[nodiscard]] std::string index_identity(const Index& index) {
  return qualified_identity(index.name);
}

[[nodiscard]] std::string policy_command_sql(const PolicyCommand command) {
  switch (command) {
  case PolicyCommand::all:
    return "ALL";
  case PolicyCommand::select:
    return "SELECT";
  case PolicyCommand::insert:
    return "INSERT";
  case PolicyCommand::update:
    return "UPDATE";
  case PolicyCommand::delete_rows:
    return "DELETE";
  }
  throw Error{ErrorCode::database, "invalid PostgreSQL policy command"};
}

[[nodiscard]] std::string policy_identity(const RowSecurityPolicy& policy) {
  return qualified_identity(policy.table) + ".policy." + policy.name;
}

[[nodiscard]] std::string render_create_policy(const RowSecurityPolicy& policy) {
  std::ostringstream sql;
  sql << "CREATE POLICY " << quote_identifier(policy.name) << " ON " << qualified_sql(policy.table)
      << " AS " << (policy.permissive ? "PERMISSIVE" : "RESTRICTIVE") << " FOR "
      << policy_command_sql(policy.command) << " TO ";
  for (std::size_t position = 0U; position < policy.roles.size(); ++position) {
    if (position != 0U) {
      sql << ", ";
    }
    sql << (policy.roles[position].public_role ? "PUBLIC"
                                               : quote_identifier(policy.roles[position].name));
  }
  if (policy.using_expression.has_value()) {
    sql << " USING (" << *policy.using_expression << ')';
  }
  if (policy.check_expression.has_value()) {
    sql << " WITH CHECK (" << *policy.check_expression << ')';
  }
  sql << ';';
  return sql.str();
}

[[nodiscard]] bool same_column_shape(const Column& left, const Column& right) {
  return left.type == right.type && left.not_null == right.not_null &&
         left.default_expression == right.default_expression && left.identity == right.identity &&
         left.generated == right.generated && left.collation == right.collation;
}

[[nodiscard]] bool same_table_shape(const Table& left, const Table& right) {
  if (left.persistence != right.persistence || left.row_security != right.row_security ||
      left.force_row_security != right.force_row_security ||
      left.columns.size() != right.columns.size()) {
    return false;
  }
  for (std::size_t index = 0U; index < left.columns.size(); ++index) {
    if (left.columns[index] != right.columns[index]) {
      return false;
    }
  }
  return true;
}

void add_diagnostic(MigrationPlan& migration_plan, std::string diagnostic) {
  migration_plan.draft = true;
  if (std::ranges::find(migration_plan.diagnostics, diagnostic) ==
      migration_plan.diagnostics.end()) {
    migration_plan.diagnostics.push_back(std::move(diagnostic));
  }
}

[[nodiscard]] std::string add_operation(MigrationPlan& migration_plan,
                                        const std::string_view action,
                                        const std::string_view identity, std::string sql,
                                        HazardSet hazards = {},
                                        std::vector<std::string> dependencies = {}) {
  const auto id = operation_id(action, identity);
  migration_plan.operations.push_back(Operation{
      .id = id,
      .object_identity = std::string{identity},
      .dependencies = std::move(dependencies),
      .transaction_mode = TransactionMode::required,
      .sql = std::move(sql),
      .hazards = std::move(hazards),
      .expected_before = {},
      .expected_after = {},
  });
  return id;
}

[[nodiscard]] std::map<QualifiedName, const Table*> table_index(const std::vector<Table>& tables) {
  std::map<QualifiedName, const Table*> result;
  for (const auto& table : tables) {
    result.emplace(table.name, &table);
  }
  return result;
}

using TableChildIdentity = std::pair<QualifiedName, std::string>;

[[nodiscard]] std::map<TableChildIdentity, const TableConstraint*>
constraint_index(const std::vector<TableConstraint>& constraints) {
  std::map<TableChildIdentity, const TableConstraint*> result;
  for (const auto& constraint : constraints) {
    result.emplace(TableChildIdentity{constraint.table, constraint.name}, &constraint);
  }
  return result;
}

[[nodiscard]] std::map<QualifiedName, const Index*> index_index(const std::vector<Index>& indexes) {
  std::map<QualifiedName, const Index*> result;
  for (const auto& index : indexes) {
    result.emplace(index.name, &index);
  }
  return result;
}

[[nodiscard]] std::map<TableChildIdentity, const RowSecurityPolicy*>
policy_index(const std::vector<RowSecurityPolicy>& policies) {
  std::map<TableChildIdentity, const RowSecurityPolicy*> result;
  for (const auto& policy : policies) {
    result.emplace(TableChildIdentity{policy.table, policy.name}, &policy);
  }
  return result;
}

[[nodiscard]] std::map<std::string, const Column*>
column_index(const std::vector<Column>& columns) {
  std::map<std::string, const Column*> result;
  for (const auto& column : columns) {
    result.emplace(column.name, &column);
  }
  return result;
}

[[nodiscard]] std::vector<std::string>
plan_row_security(MigrationPlan& migration_plan, const Table& from, const Table& to,
                  std::vector<std::string> dependencies = {}) {
  const auto table = qualified_sql(to.name);
  const auto identity = qualified_identity(to.name);
  if (from.row_security != to.row_security) {
    const auto action =
        to.row_security ? "table.row_security.enable" : "table.row_security.disable";
    const auto sql =
        "ALTER TABLE " + table +
        (to.row_security ? " ENABLE ROW LEVEL SECURITY;" : " DISABLE ROW LEVEL SECURITY;");
    dependencies = {add_operation(migration_plan, action, identity, sql,
                                  HazardSet{Hazard::write_lock}, std::move(dependencies))};
  }
  if (from.force_row_security != to.force_row_security) {
    const auto action =
        to.force_row_security ? "table.row_security.force" : "table.row_security.no_force";
    const auto sql =
        "ALTER TABLE " + table +
        (to.force_row_security ? " FORCE ROW LEVEL SECURITY;" : " NO FORCE ROW LEVEL SECURITY;");
    dependencies = {add_operation(migration_plan, action, identity, sql,
                                  HazardSet{Hazard::write_lock}, std::move(dependencies))};
  }
  return dependencies;
}

} // namespace

MigrationPlan plan(SchemaSnapshot from, SchemaSnapshot to) {
  from = normalize_snapshot(std::move(from));
  to = normalize_snapshot(std::move(to));
  if (from.server_version.major != to.server_version.major) {
    throw Error{ErrorCode::unsupported,
                "PostgreSQL planning requires snapshots from the same server major version"};
  }

  MigrationPlan migration_plan;
  const std::set<std::string, std::less<>> from_schemas(from.schemas.begin(), from.schemas.end());
  const std::set<std::string, std::less<>> to_schemas(to.schemas.begin(), to.schemas.end());
  const auto from_tables = table_index(from.tables);
  const auto to_tables = table_index(to.tables);
  const auto from_constraints = constraint_index(from.constraints);
  const auto to_constraints = constraint_index(to.constraints);
  const auto from_indexes = index_index(from.indexes);
  const auto to_indexes = index_index(to.indexes);
  const auto from_policies = policy_index(from.policies);
  const auto to_policies = policy_index(to.policies);

  const auto append_dependencies = [](std::vector<std::string>& dependencies,
                                      const std::vector<std::string>& additions) {
    for (const auto& addition : additions) {
      if (std::ranges::find(dependencies, addition) == dependencies.end()) {
        dependencies.push_back(addition);
      }
    }
  };
  const auto append_dependency = [](std::vector<std::string>& dependencies,
                                    const std::string& addition) {
    if (std::ranges::find(dependencies, addition) == dependencies.end()) {
      dependencies.push_back(addition);
    }
  };

  std::map<std::string, std::string, std::less<>> schema_create_operations;
  for (const auto& schema : to_schemas) {
    if (!from_schemas.contains(schema)) {
      schema_create_operations.emplace(
          schema, add_operation(migration_plan, "schema.create", schema,
                                "CREATE SCHEMA " + quote_identifier(schema) + ";"));
    }
  }

  std::set<QualifiedName> possible_table_renames_from;
  std::set<QualifiedName> possible_table_renames_to;
  for (const auto& [from_name, from_table] : from_tables) {
    if (to_tables.contains(from_name)) {
      continue;
    }
    for (const auto& [to_name, to_table] : to_tables) {
      if (!from_tables.contains(to_name) && same_table_shape(*from_table, *to_table)) {
        possible_table_renames_from.insert(from_name);
        possible_table_renames_to.insert(to_name);
        add_diagnostic(migration_plan, "possible table rename from " + qualified_sql(from_name) +
                                           " to " + qualified_sql(to_name) +
                                           "; write an explicit ALTER TABLE ... RENAME migration");
      }
    }
  }

  std::set<QualifiedName> relational_blocked_tables;
  for (const auto& [name, source_table] : from_tables) {
    const auto target = to_tables.find(name);
    if (target == to_tables.end()) {
      continue;
    }
    const auto source_columns = column_index(source_table->columns);
    const auto target_columns = column_index(target->second->columns);
    for (const auto& [source_name, source_column] : source_columns) {
      if (target_columns.contains(source_name)) {
        continue;
      }
      for (const auto& [target_name, target_column] : target_columns) {
        if (!source_columns.contains(target_name) &&
            same_column_shape(*source_column, *target_column)) {
          relational_blocked_tables.insert(name);
          break;
        }
      }
    }
  }

  const auto blocked_source_table = [&](const QualifiedName& table) {
    return possible_table_renames_from.contains(table) || relational_blocked_tables.contains(table);
  };
  const auto blocked_target_table = [&](const QualifiedName& table) {
    return possible_table_renames_to.contains(table) || relational_blocked_tables.contains(table);
  };

  std::set<QualifiedName> changed_unique_tables;
  for (const auto& [identity, constraint] : from_constraints) {
    if (blocked_source_table(constraint->table) ||
        (constraint->kind != ConstraintKind::primary_key &&
         constraint->kind != ConstraintKind::unique)) {
      continue;
    }
    const auto target = to_constraints.find(identity);
    if (target == to_constraints.end() || *target->second != *constraint) {
      changed_unique_tables.insert(constraint->table);
    }
  }
  for (const auto& [identity, constraint] : to_constraints) {
    if (blocked_target_table(constraint->table) ||
        (constraint->kind != ConstraintKind::primary_key &&
         constraint->kind != ConstraintKind::unique)) {
      continue;
    }
    const auto source = from_constraints.find(identity);
    if (source == from_constraints.end() || *source->second != *constraint) {
      changed_unique_tables.insert(constraint->table);
    }
  }
  for (const auto& [identity, index] : from_indexes) {
    if (!index->unique || blocked_source_table(index->table)) {
      continue;
    }
    const auto target = to_indexes.find(identity);
    if (target == to_indexes.end() || *target->second != *index) {
      changed_unique_tables.insert(index->table);
    }
  }
  for (const auto& [identity, index] : to_indexes) {
    if (!index->unique || blocked_target_table(index->table)) {
      continue;
    }
    const auto source = from_indexes.find(identity);
    if (source == from_indexes.end() || *source->second != *index) {
      changed_unique_tables.insert(index->table);
    }
  }

  const auto constraint_requires_drop = [&](const TableChildIdentity& identity,
                                            const TableConstraint& constraint) {
    if (blocked_source_table(constraint.table)) {
      return false;
    }
    const auto target = to_constraints.find(identity);
    return target == to_constraints.end() || *target->second != constraint ||
           (constraint.kind == ConstraintKind::foreign_key &&
            constraint.referenced_table.has_value() &&
            changed_unique_tables.contains(*constraint.referenced_table));
  };
  const auto constraint_requires_create = [&](const TableChildIdentity& identity,
                                              const TableConstraint& constraint) {
    if (blocked_target_table(constraint.table)) {
      return false;
    }
    const auto source = from_constraints.find(identity);
    return source == from_constraints.end() || *source->second != constraint ||
           (constraint.kind == ConstraintKind::foreign_key &&
            constraint.referenced_table.has_value() &&
            changed_unique_tables.contains(*constraint.referenced_table));
  };

  std::map<QualifiedName, std::vector<std::string>> structural_prerequisites;
  std::map<QualifiedName, std::vector<std::string>> inbound_foreign_key_drops;

  for (const auto& [identity, policy] : from_policies) {
    if (blocked_source_table(policy->table)) {
      continue;
    }
    const auto target = to_policies.find(identity);
    if (target == to_policies.end() || *target->second != *policy) {
      const auto id = add_operation(migration_plan, "policy.drop", policy_identity(*policy),
                                    "DROP POLICY " + quote_identifier(policy->name) + " ON " +
                                        qualified_sql(policy->table) + ";",
                                    HazardSet{Hazard::write_lock});
      structural_prerequisites[policy->table].push_back(id);
    }
  }

  for (const auto& [identity, constraint] : from_constraints) {
    if (constraint->kind != ConstraintKind::foreign_key ||
        !constraint_requires_drop(identity, *constraint)) {
      continue;
    }
    const auto id =
        add_operation(migration_plan, "constraint.drop", constraint_identity(*constraint),
                      render_drop_constraint(*constraint), HazardSet{Hazard::write_lock});
    append_dependency(structural_prerequisites[constraint->table], id);
    if (constraint->referenced_table.has_value()) {
      append_dependency(structural_prerequisites[*constraint->referenced_table], id);
      append_dependency(inbound_foreign_key_drops[*constraint->referenced_table], id);
    }
  }

  std::map<QualifiedName, std::vector<std::string>> non_not_null_constraint_drops;
  for (const auto& [identity, constraint] : from_constraints) {
    if (constraint->kind == ConstraintKind::foreign_key ||
        constraint->kind == ConstraintKind::not_null ||
        !constraint_requires_drop(identity, *constraint)) {
      continue;
    }
    std::vector<std::string> dependencies;
    if (constraint->kind == ConstraintKind::primary_key ||
        constraint->kind == ConstraintKind::unique) {
      append_dependencies(dependencies, inbound_foreign_key_drops[constraint->table]);
    }
    const auto id =
        add_operation(migration_plan, "constraint.drop", constraint_identity(*constraint),
                      render_drop_constraint(*constraint), HazardSet{Hazard::write_lock},
                      std::move(dependencies));
    structural_prerequisites[constraint->table].push_back(id);
    non_not_null_constraint_drops[constraint->table].push_back(id);
  }

  for (const auto& [identity, constraint] : from_constraints) {
    if (constraint->kind != ConstraintKind::not_null ||
        !constraint_requires_drop(identity, *constraint)) {
      continue;
    }
    auto dependencies = non_not_null_constraint_drops[constraint->table];
    const auto id =
        add_operation(migration_plan, "constraint.drop", constraint_identity(*constraint),
                      render_drop_constraint(*constraint), HazardSet{Hazard::write_lock},
                      std::move(dependencies));
    structural_prerequisites[constraint->table].push_back(id);
  }

  for (const auto& [identity, index] : from_indexes) {
    if (blocked_source_table(index->table)) {
      continue;
    }
    const auto target = to_indexes.find(identity);
    if (target == to_indexes.end() || *target->second != *index) {
      std::vector<std::string> dependencies;
      if (index->unique) {
        append_dependencies(dependencies, inbound_foreign_key_drops[index->table]);
      }
      const auto id = add_operation(migration_plan, "index.drop", index_identity(*index),
                                    "DROP INDEX " + qualified_sql(index->name) + " RESTRICT;",
                                    HazardSet{Hazard::write_lock}, std::move(dependencies));
      structural_prerequisites[index->table].push_back(id);
    }
  }

  std::map<std::string, std::vector<std::string>, std::less<>> dropped_table_operations;
  std::map<QualifiedName, std::vector<std::string>> table_tail_operations;
  for (const auto& [name, table] : to_tables) {
    if (from_tables.contains(name) || possible_table_renames_to.contains(name)) {
      continue;
    }
    std::vector<std::string> dependencies;
    if (const auto schema = schema_create_operations.find(name.schema);
        schema != schema_create_operations.end()) {
      dependencies.push_back(schema->second);
    }
    const auto create_id =
        add_operation(migration_plan, "table.create", qualified_identity(name),
                      render_create_table(*table, to.constraints), {}, std::move(dependencies));
    const Table empty_table{
        .name = name,
        .persistence = table->persistence,
        .row_security = false,
        .force_row_security = false,
        .columns = table->columns,
    };
    table_tail_operations[name] =
        plan_row_security(migration_plan, empty_table, *table, {create_id});
  }

  for (const auto& [name, from_table] : from_tables) {
    const auto target = to_tables.find(name);
    if (target == to_tables.end()) {
      if (!possible_table_renames_from.contains(name)) {
        auto dependencies = structural_prerequisites[name];
        const auto id = add_operation(migration_plan, "table.drop", qualified_identity(name),
                                      "DROP TABLE " + qualified_sql(name) + " RESTRICT;",
                                      HazardSet{Hazard::data_loss, Hazard::write_lock},
                                      std::move(dependencies));
        dropped_table_operations[name.schema].push_back(id);
      }
      continue;
    }

    const auto* to_table = target->second;
    auto table_dependencies = structural_prerequisites[name];
    if (from_table->persistence != to_table->persistence) {
      const auto sql =
          "ALTER TABLE " + qualified_sql(name) +
          (to_table->persistence == TablePersistence::unlogged ? " SET UNLOGGED;" : " SET LOGGED;");
      table_dependencies = {add_operation(
          migration_plan, "table.persistence", qualified_identity(name), sql,
          HazardSet{Hazard::table_rewrite, Hazard::write_lock}, std::move(table_dependencies))};
    }

    const auto from_columns = column_index(from_table->columns);
    const auto to_columns = column_index(to_table->columns);
    std::set<std::string, std::less<>> possible_column_renames_from;
    std::set<std::string, std::less<>> possible_column_renames_to;
    for (const auto& [from_name, from_column] : from_columns) {
      if (to_columns.contains(from_name)) {
        continue;
      }
      for (const auto& [to_name, to_column] : to_columns) {
        if (!from_columns.contains(to_name) && same_column_shape(*from_column, *to_column)) {
          possible_column_renames_from.insert(from_name);
          possible_column_renames_to.insert(to_name);
          add_diagnostic(migration_plan,
                         "possible column rename from " + quote_identifier(from_name) + " to " +
                             quote_identifier(to_name) + " on " + qualified_sql(name) +
                             "; write an explicit RENAME COLUMN migration");
          relational_blocked_tables.insert(name);
        }
      }
    }

    std::vector<std::string> from_common_order;
    std::vector<std::string> to_common_order;
    for (const auto& column : from_table->columns) {
      if (to_columns.contains(column.name)) {
        from_common_order.push_back(column.name);
      }
    }
    bool saw_added_column = false;
    std::set<std::string, std::less<>> inserted_columns;
    for (const auto& column : to_table->columns) {
      if (from_columns.contains(column.name)) {
        to_common_order.push_back(column.name);
        if (saw_added_column) {
          for (const auto& candidate : to_table->columns) {
            if (!from_columns.contains(candidate.name) && candidate.position < column.position) {
              inserted_columns.insert(candidate.name);
            }
          }
        }
      } else {
        saw_added_column = true;
      }
    }
    if (from_common_order != to_common_order) {
      relational_blocked_tables.insert(name);
      add_diagnostic(migration_plan, "column reordering on " + qualified_sql(name) +
                                         " cannot be represented safely by PostgreSQL ALTER TABLE");
    }
    for (const auto& inserted : inserted_columns) {
      relational_blocked_tables.insert(name);
      add_diagnostic(migration_plan,
                     "column " + quote_identifier(inserted) + " is inserted into the middle of " +
                         qualified_sql(name) +
                         "; PostgreSQL ADD COLUMN can only append it without rebuilding the table");
    }

    for (const auto& column : from_table->columns) {
      if (!to_columns.contains(column.name) &&
          !possible_column_renames_from.contains(column.name)) {
        table_dependencies = {
            add_operation(migration_plan, "column.drop", column_identity(name, column.name),
                          "ALTER TABLE " + qualified_sql(name) + " DROP COLUMN " +
                              quote_identifier(column.name) + " RESTRICT;",
                          HazardSet{Hazard::data_loss, Hazard::write_lock}, table_dependencies)};
      }
    }

    for (const auto& column : to_table->columns) {
      if (from_columns.contains(column.name) || possible_column_renames_to.contains(column.name) ||
          inserted_columns.contains(column.name)) {
        continue;
      }
      if (column.not_null && !column.default_expression.has_value() &&
          column.identity == IdentityGeneration::none &&
          column.generated == GeneratedStorage::none) {
        add_diagnostic(migration_plan, "adding NOT NULL column " + quote_identifier(column.name) +
                                           " to " + qualified_sql(name) +
                                           " requires an explicit backfill/default migration");
        relational_blocked_tables.insert(name);
        continue;
      }
      HazardSet hazards{Hazard::write_lock};
      if (column.default_expression.has_value() || column.generated != GeneratedStorage::none) {
        hazards.insert(Hazard::table_rewrite);
      }
      table_dependencies = {add_operation(
          migration_plan, "column.add", column_identity(name, column.name),
          "ALTER TABLE " + qualified_sql(name) + " ADD COLUMN " +
              render_column_definition(
                  column, !has_not_null_constraint(to.constraints, name, column.name)) +
              ";",
          std::move(hazards), table_dependencies)};
    }

    for (const auto& from_column : from_table->columns) {
      const auto target_column = to_columns.find(from_column.name);
      if (target_column == to_columns.end()) {
        continue;
      }
      const auto& to_column = *target_column->second;
      const bool generated_expression_changed =
          from_column.generated != GeneratedStorage::none &&
          from_column.default_expression != to_column.default_expression;
      if (from_column.type != to_column.type || from_column.identity != to_column.identity ||
          from_column.generated != to_column.generated ||
          from_column.collation != to_column.collation || generated_expression_changed) {
        add_diagnostic(migration_plan,
                       "column " + quote_identifier(from_column.name) + " on " +
                           qualified_sql(name) +
                           " changes type, collation, identity, or generation semantics; write an "
                           "explicit ALTER COLUMN migration with any required USING expression");
        relational_blocked_tables.insert(name);
        continue;
      }

      if (from_column.generated == GeneratedStorage::none &&
          from_column.identity == IdentityGeneration::none &&
          from_column.default_expression != to_column.default_expression) {
        const auto sql = to_column.default_expression.has_value()
                             ? "ALTER TABLE " + qualified_sql(name) + " ALTER COLUMN " +
                                   quote_identifier(from_column.name) + " SET DEFAULT " +
                                   *to_column.default_expression + ";"
                             : "ALTER TABLE " + qualified_sql(name) + " ALTER COLUMN " +
                                   quote_identifier(from_column.name) + " DROP DEFAULT;";
        table_dependencies = {add_operation(
            migration_plan,
            to_column.default_expression.has_value() ? "column.default.set" : "column.default.drop",
            column_identity(name, from_column.name), sql, HazardSet{Hazard::write_lock},
            table_dependencies)};
      }
      if (from_column.not_null != to_column.not_null) {
        const auto target_constraint_sets_not_null =
            std::ranges::any_of(to.constraints, [&](const TableConstraint& constraint) {
              return constraint.table == name &&
                     (constraint.kind == ConstraintKind::primary_key ||
                      constraint.kind == ConstraintKind::not_null) &&
                     std::ranges::find(constraint.columns, from_column.name) !=
                         constraint.columns.end();
            });
        const auto source_named_not_null_dropped =
            !to_column.not_null &&
            has_not_null_constraint(from.constraints, name, from_column.name);
        if (target_constraint_sets_not_null || source_named_not_null_dropped) {
          continue;
        }
        HazardSet hazards{Hazard::write_lock};
        if (to_column.not_null) {
          hazards.insert(Hazard::constraint_scan);
        }
        const auto sql = "ALTER TABLE " + qualified_sql(name) + " ALTER COLUMN " +
                         quote_identifier(from_column.name) +
                         (to_column.not_null ? " SET NOT NULL;" : " DROP NOT NULL;");
        table_dependencies = {add_operation(
            migration_plan, to_column.not_null ? "column.not_null.set" : "column.not_null.drop",
            column_identity(name, from_column.name), sql, std::move(hazards), table_dependencies)};
      }
    }
    table_tail_operations[name] =
        plan_row_security(migration_plan, *from_table, *to_table, std::move(table_dependencies));
  }

  std::map<QualifiedName, std::vector<std::string>> key_create_operations;
  const auto constraint_hazards = [](const TableConstraint& constraint) {
    HazardSet hazards{Hazard::write_lock};
    if (constraint.validated && constraint.enforced) {
      hazards.insert(Hazard::constraint_scan);
    }
    return hazards;
  };

  std::map<QualifiedName, std::vector<std::string>> not_null_create_operations;
  for (const auto& [identity, constraint] : to_constraints) {
    if (constraint->kind != ConstraintKind::not_null ||
        !constraint_requires_create(identity, *constraint) ||
        relational_blocked_tables.contains(constraint->table)) {
      continue;
    }
    auto dependencies = table_tail_operations[constraint->table];
    const auto id =
        add_operation(migration_plan, "constraint.create", constraint_identity(*constraint),
                      render_add_constraint(*constraint), constraint_hazards(*constraint),
                      std::move(dependencies));
    not_null_create_operations[constraint->table].push_back(id);
  }

  for (const auto& [identity, constraint] : to_constraints) {
    if (constraint->kind == ConstraintKind::foreign_key ||
        constraint->kind == ConstraintKind::not_null ||
        !constraint_requires_create(identity, *constraint) ||
        relational_blocked_tables.contains(constraint->table)) {
      continue;
    }
    auto dependencies = table_tail_operations[constraint->table];
    append_dependencies(dependencies, not_null_create_operations[constraint->table]);
    const auto id =
        add_operation(migration_plan, "constraint.create", constraint_identity(*constraint),
                      render_add_constraint(*constraint), constraint_hazards(*constraint),
                      std::move(dependencies));
    if (constraint->kind == ConstraintKind::primary_key ||
        constraint->kind == ConstraintKind::unique) {
      key_create_operations[constraint->table].push_back(id);
    }
  }

  for (const auto& [identity, index] : to_indexes) {
    if (blocked_target_table(index->table) || relational_blocked_tables.contains(index->table)) {
      continue;
    }
    const auto source = from_indexes.find(identity);
    if (source != from_indexes.end() && *source->second == *index) {
      continue;
    }
    auto dependencies = table_tail_operations[index->table];
    const auto id = add_operation(migration_plan, "index.create", index_identity(*index),
                                  render_create_index(*index), HazardSet{Hazard::write_lock},
                                  std::move(dependencies));
    if (index->unique) {
      key_create_operations[index->table].push_back(id);
    }
  }

  for (const auto& [identity, constraint] : to_constraints) {
    if (constraint->kind != ConstraintKind::foreign_key ||
        !constraint_requires_create(identity, *constraint) ||
        relational_blocked_tables.contains(constraint->table)) {
      continue;
    }
    auto dependencies = table_tail_operations[constraint->table];
    if (constraint->referenced_table.has_value()) {
      append_dependencies(dependencies, table_tail_operations[*constraint->referenced_table]);
      append_dependencies(dependencies, key_create_operations[*constraint->referenced_table]);
    }
    static_cast<void>(add_operation(migration_plan, "constraint.create",
                                    constraint_identity(*constraint),
                                    render_add_constraint(*constraint),
                                    constraint_hazards(*constraint), std::move(dependencies)));
  }

  for (const auto& [identity, policy] : to_policies) {
    if (blocked_target_table(policy->table) || relational_blocked_tables.contains(policy->table)) {
      continue;
    }
    const auto source = from_policies.find(identity);
    if (source != from_policies.end() && *source->second == *policy) {
      continue;
    }
    static_cast<void>(add_operation(migration_plan, "policy.create", policy_identity(*policy),
                                    render_create_policy(*policy), HazardSet{Hazard::write_lock},
                                    table_tail_operations[policy->table]));
  }

  for (const auto& schema : from_schemas) {
    if (to_schemas.contains(schema)) {
      continue;
    }
    const bool blocked_table =
        std::ranges::any_of(possible_table_renames_from,
                            [&schema](const QualifiedName& name) { return name.schema == schema; });
    if (blocked_table) {
      add_diagnostic(migration_plan,
                     "schema " + quote_identifier(schema) +
                         " cannot be dropped while a possible table rename is unresolved");
      continue;
    }
    auto dependencies = dropped_table_operations[schema];
    static_cast<void>(add_operation(migration_plan, "schema.drop", schema,
                                    "DROP SCHEMA " + quote_identifier(schema) + " RESTRICT;", {},
                                    std::move(dependencies)));
  }

  return migration_plan;
}

std::string render_plan(const MigrationPlan& migration_plan) {
  std::ostringstream sql;
  if (migration_plan.draft) {
    sql << "-- draft: manual edits required\n";
    for (const auto& diagnostic : migration_plan.diagnostics) {
      std::string single_line = diagnostic;
      std::ranges::replace(single_line, '\n', ' ');
      sql << "-- TODO: " << single_line << '\n';
    }
  }
  if (migration_plan.operations.empty()) {
    return sql.str();
  }

  const auto order = deterministic_operation_order(migration_plan.operations);
  for (const auto index : order) {
    if (migration_plan.operations[index].transaction_mode == TransactionMode::forbidden) {
      throw Error{ErrorCode::unsupported,
                  "PostgreSQL focused planner cannot render nontransactional operations"};
    }
  }
  sql << "BEGIN;\n";
  for (const auto index : order) {
    const auto& operation = migration_plan.operations[index];
    if (!operation.hazards.empty()) {
      sql << "-- hazards:";
      for (const auto hazard : operation.hazards) {
        sql << ' ' << hazard_name(hazard);
      }
      sql << '\n';
    }
    sql << operation.sql;
    if (!operation.sql.ends_with('\n')) {
      sql << '\n';
    }
  }
  sql << "COMMIT;\n";
  return sql.str();
}

} // namespace dbdiff::postgresql
