CREATE TABLE app.users (
  id bigint GENERATED ALWAYS AS IDENTITY,
  email text NOT NULL,
  state text NOT NULL DEFAULT 'invited',
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_email_key UNIQUE (email),
  CONSTRAINT users_state_check CHECK (state IN ('invited', 'active', 'disabled'))
);

CREATE TABLE app.sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id bigint NOT NULL,
  token text NOT NULL,
  payload text,
  revoked_at timestamptz,
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_user_fkey
    FOREIGN KEY (user_id) REFERENCES app.users (id) ON DELETE CASCADE
);
